package com.oyms.model;

import java.util.Date;

import org.springframework.stereotype.Component;
@Component
public class GoodType {

    private Integer id;

    private Integer parentId;

    private String cname;

    private Byte isdelete;

    private Date createTime;

    private String imgSrc;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.id
     *
     * @param id the value for goodtype.id
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.parent_id
     *
     * @return the value of goodtype.parent_id
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.parent_id
     *
     * @param parentId the value for goodtype.parent_id
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.cname
     *
     * @return the value of goodtype.cname
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.cname
     *
     * @param cname the value for goodtype.cname
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.isdelete
     *
     * @return the value of goodtype.isdelete
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.isdelete
     *
     * @param isdelete the value for goodtype.isdelete
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.create_time
     *
     * @return the value of goodtype.create_time
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.create_time
     *
     * @param createTime the value for goodtype.create_time
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.img_src
     *
     * @return the value of goodtype.img_src
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public String getImgSrc() {
        return imgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.img_src
     *
     * @param imgSrc the value for goodtype.img_src
     *
     * @mbg.generated Wed Nov 06 21:44:37 CST 2019
     */
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc == null ? null : imgSrc.trim();
    }
}